layout_spectrum: 0.7086319225950922
typography_spectrum: 0.6646379033356241
color:
  brandStrength: 0.7672217673676476
  lightness: 0.020044311027937006
  saturation: 0.6026478751258242
  rhythmicContrast: 0.851244239857199
  brandColors:
    - '#FFF8E3'
    - '#CCCC9F'
    - '#33332D'
    - '#9FB4CC'
    - '#DB4105'
coverPrefs:
  filter: false
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/fe67f033-01bb-495d-bd3a-0d969ee360b8.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/fe67f033-01bb-495d-bd3a-0d969ee360b8.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
title: 'Inspiration and More :)'
content_rating:
  adult: false
github: true
author: {}
name: yoco2
analytics: {}
opengraph: {}
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
description: YOCO Your Communication GmbH - Brand Design und Integrierte Komminikation
purpose:
  - type: contact
    url: 'tel:+41522033454'
    label: Call +41 52 203 34 54
