layout_spectrum: 0.7086319225950922
typography_spectrum: 0.6646379033356241
color:
  brandStrength: 0.7672217673676476
  lightness: 0.020044311027937006
  saturation: 0.6026478751258242
  rhythmicContrast: 0.851244239857199
  brandColors:
    - '#FFF8E3'
    - '#CCCC9F'
    - '#33332D'
    - '#9FB4CC'
    - '#DB4105'
coverPrefs:
  filter: false
content: []
title: 'Inspiration and More :)'
content_rating:
  adult: false
github: true
author: {}
name: yoco2
analytics: {}
opengraph: {}
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
description: YOCO Your Communication GmbH - Brand Design und Integreirte Komminikation
